### PR TITLE
fix: redeploy full build when a deploy is in error state

### LINKED ISSUE #9: Docker services don't deploy if initial deploy has a build failure
Fairly easy to reproduce this issue.
1. Setup a github build - Something like a basic typescript app
2. Add in a postgres dependency
3. Intentionally make the typescript build fail, so that the build step isn't successful
4. Go fix that issue and push the change
5. The postgres instance won't deploy out alongside the typescript app. Removing the lifecycle label fixes the issue.

### PR DESCRIPTION
**Pull request by vigneshrajsb**
## What
Fixes #9 

With selective deploy, when app receives a commit push, we only deploy the services that are configured in the repo with the commit.  

if we have docker, aurora-restore types that are not mapped with `githubRepositoryId` in `deploys` table, we wont rebuild these services on a push. 

So we add a conditional check to see if any of the active `deploys` have an error status before we add the `build` to build queue to either redeploy the full build if there are errored deploys to avoid the gap in workflow

### CODE REVIEW

File: src/server/services/github.ts [hunk 1]
```diff
@@ -327,10 +333,26 @@ export default class GithubService extends Service {
         if (!buildId) {
           logger.error(`[BUILD ${build?.uuid}][handlePushWebhook][buidIdError] No build ID found for this build!`);
         }
-        logger.info(`[BUILD ${build?.uuid}] Deploying build for push on repo: ${repoName} branch: ${branchName}`);
+
+        // Check if any deploys for this build have failed previously
+        const failedDeploys = await models.Deploy.query()
+          .where('buildId', buildId)
+          .where('active', true)
+          .whereIn('status', [DeployStatus.ERROR, DeployStatus.BUILD_FAILED, DeployStatus.DEPLOY_FAILED]);
```
Comment (vigneshrajsb) [inline src/server/services/github.ts]: if we add new status that mean error, should be added here.  maybe we could refactor how we define and maintain status later

**Review by vmelikyan — APPROVED** [review]
